//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wardrobe.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;     //Added to enable Display Name alteration

    public partial class Accessory
    {
        //generated when ado.net entity was added
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Accessory()
        {
            //initializing foreign key column in Outfits table
            this.Outfits = new HashSet<Outfit>();
        }
    //Accessory table, Display names altered AccessoryID as primary key
        public int AccessoryID { get; set; }
        [Display(Name = "Name")]
        public string AccessoryName { get; set; }
        [Display(Name = "Color")]
        public string AccessoryColor { get; set; }
        [Display(Name = "Occasion")]
        public string AccessoryOccasion { get; set; }
        [Display(Name = "Season")]
        public string AccessorySeason { get; set; }
        public string AccessoryPhoto { get; set; }

    //AccessoryID is Foreign key in Outfits table
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Outfit> Outfits { get; set; }
    }
}
