//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wardrobe.Models
{
    using System;
    using System.ComponentModel.DataAnnotations;     //added to enable display name changes
    using System.Collections.Generic;
    
    public partial class Bottom
    {
        //generated when ado.net enity is created
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bottom()
        {
            //initializes foreign ket column in Outfits table
            this.Outfits = new HashSet<Outfit>();
        }
    //Bottoms table, display names altered, BottomsID is primary key
        public int BottomsID { get; set; }
        [Display(Name = "Name")]
        public string BottomsName { get; set; }
        [Display(Name = "Color")]
        public string BottomsColor { get; set; }
        [Display(Name = "Occassion")]
        public string BottomsOccasion { get; set; }
        [Display(Name = "Season")]
        public string BottomsSeason { get; set; }
        public string BottomsPhoto { get; set; }
    
        //BottomsID is foreign key in Outfits table
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Outfit> Outfits { get; set; }
    }
}
