//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wardrobe.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;   //added to eneable display name changes

    public partial class Sho
    {
        //generated when ado.net entity was created
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sho()
        {
            //initialized foreign key column in Outfits table
                       this.Outfits = new HashSet<Outfit>();
        }
    //Shoes table, Display names altererd, ShoesID is primary key
        public int ShoesID { get; set; }
        [Display(Name = "Name")]
        public string ShoesName { get; set; }
        [Display(Name = "Color")]
        public string ShoesColor { get; set; }
        [Display(Name = "Occasion")]
        public string ShoesOccasion { get; set; }
        [Display(Name = "Season")]
        public string ShoesSeason { get; set; }
        public string ShoesPhoto { get; set; }
    
        //ShoesID is foreign key in Outfits table
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Outfit> Outfits { get; set; }
    }
}
