//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wardrobe.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;  //added to enable display name alterations

    public partial class Top
    {
        //generated when ado.net entity was created
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Top()
        {
            this.Outfits = new HashSet<Outfit>();
        }
    //Tops table, Display names altered, TopsID is primary key
        public int TopsID { get; set; }
        [Display(Name = "Name")]
        public string TopsName { get; set; }
        [Display(Name = "Color")]
        public string TopsColor { get; set; }
        [Display(Name = "Occasion")]
        public string TopsOccasion { get; set; }
        [Display(Name = "Season")]
        public string TopsSeason { get; set; }
        public string TopsPhoto { get; set; }
    
        //TopsID is foreign key in Outfits table
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Outfit> Outfits { get; set; }
    }
}
